### PR TITLE
Deliverd and canceld orders

### PR DESCRIPTION
**Pull request by fraidy1**
this is with changes from the other pull request i copied it to a deferent branch becoas thay were a lot of conflictim

### CODE REVIEW

**Comment by fraidy1** [comment]
with changes from the cancledm deliverd orders request

**Comment by moriyahazan** [comment]
@fraidy1  why is this pull request still open???

please close not relevant PR or fix and merge them

**Comment by fraidy1** [comment]
this pull request I need you to Approve so i can merge
thanks

**Review by moriyahazan — APPROVED** [review]
Very nice 
well done

**Pull request merged**
