### PR TITLE
top product aggregation

### PR DESCRIPTION
**Pull request by sara1386**
errors with top product aggregation

### CODE REVIEW

**Comment by moriyahazan** [comment]
What is the error? please details 
In addition you have compilation errors

**Comment by moriyahazan** [comment]
I am waiting for your answer
 please see my question from 2 weeks ago
and please fix compilation error there is in your branch

**Comment by sara1386** [comment]
Hi Moriya,
I apologize; I responded to you via email. I'm sorry you didn't see it.
This is the code I copied from mongo compass to run the aggregation I wrote.
With the stages it works perfectly.
However in this stage I just don't know how to continue...

**Review by avigailRo — APPROVED** [review]
כל הכבוד!

**Comment by sara1386** [comment]
#27 Motiya, I sow you added commits to this pull request. did you try it out yourself? cas by me it returns an empty array

**Pull request merged**
